# config/cucumber.yml
##YAML Template
---
win7: -f junit features/wgoc_check_kai.feature --out .
xp: -f junit features/wgoc_check_kai.feature --out C:/Documents and Settings/work/.jenkins/workspace/wg_merchant_oc_regression/